// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5OULwRUgTTAgHSwxrRnu1OZh6WMXUFiQ',
    appId: '1:945078321438:web:e9ef496eb5fd9403f4490f',
    messagingSenderId: '945078321438',
    projectId: 'chatapptute-362c3',
    authDomain: 'chatapptute-362c3.firebaseapp.com',
    storageBucket: 'chatapptute-362c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2s-FfUbjoXsPgv0KvngQoX_KifMtXeLU',
    appId: '1:945078321438:android:9f7bdaded60ba1ccf4490f',
    messagingSenderId: '945078321438',
    projectId: 'chatapptute-362c3',
    storageBucket: 'chatapptute-362c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqQzkJJ4wn24m9TZs35DWl2kwHGyLQGk',
    appId: '1:945078321438:ios:97099b6ac2fc3648f4490f',
    messagingSenderId: '945078321438',
    projectId: 'chatapptute-362c3',
    storageBucket: 'chatapptute-362c3.appspot.com',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmqQzkJJ4wn24m9TZs35DWl2kwHGyLQGk',
    appId: '1:945078321438:ios:410297ed53f7db4cf4490f',
    messagingSenderId: '945078321438',
    projectId: 'chatapptute-362c3',
    storageBucket: 'chatapptute-362c3.appspot.com',
    iosBundleId: 'com.example.chatapptute.RunnerTests',
  );
}
