// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC9l9aIMSV5J4sk8lW42_fopG_fXnlPvw',
    appId: '1:388166436544:web:1adb87c75b79cd07e68f25',
    messagingSenderId: '388166436544',
    projectId: 'crudstuff-a1d08',
    authDomain: 'crudstuff-a1d08.firebaseapp.com',
    storageBucket: 'crudstuff-a1d08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmYVuEDUv2c3lWB9mSRuU-RssPMgL-ps',
    appId: '1:388166436544:android:fe94e3147a9bb94ee68f25',
    messagingSenderId: '388166436544',
    projectId: 'crudstuff-a1d08',
    storageBucket: 'crudstuff-a1d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDxXvNV4aPSZBBtBNZgg8-pLuzZx5M2Y',
    appId: '1:388166436544:ios:e0e0f890ba0899c9e68f25',
    messagingSenderId: '388166436544',
    projectId: 'crudstuff-a1d08',
    storageBucket: 'crudstuff-a1d08.appspot.com',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDxXvNV4aPSZBBtBNZgg8-pLuzZx5M2Y',
    appId: '1:388166436544:ios:e0e0f890ba0899c9e68f25',
    messagingSenderId: '388166436544',
    projectId: 'crudstuff-a1d08',
    storageBucket: 'crudstuff-a1d08.appspot.com',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC9l9aIMSV5J4sk8lW42_fopG_fXnlPvw',
    appId: '1:388166436544:web:ee1a2ba63fc9887ee68f25',
    messagingSenderId: '388166436544',
    projectId: 'crudstuff-a1d08',
    authDomain: 'crudstuff-a1d08.firebaseapp.com',
    storageBucket: 'crudstuff-a1d08.appspot.com',
  );
}
