// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfM08PdDObT2hFVThyzlcOLfd7uzVfiBo',
    appId: '1:359451658384:web:2f0aeb917399aab9293015',
    messagingSenderId: '359451658384',
    projectId: 'hw7thing',
    authDomain: 'hw7thing.firebaseapp.com',
    storageBucket: 'hw7thing.appspot.com',
    measurementId: 'G-HPWB2M5RZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv899IJsGwWchHVgwgHEisIJFXhzs4cr8',
    appId: '1:359451658384:android:69ce39c0aba3f8e6293015',
    messagingSenderId: '359451658384',
    projectId: 'hw7thing',
    storageBucket: 'hw7thing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXLmRQMIdgeAfTOeQkZq9GhpQR9odG3Q',
    appId: '1:359451658384:ios:c22ff21b6f92de40293015',
    messagingSenderId: '359451658384',
    projectId: 'hw7thing',
    storageBucket: 'hw7thing.appspot.com',
    iosBundleId: 'com.example.bookme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxXLmRQMIdgeAfTOeQkZq9GhpQR9odG3Q',
    appId: '1:359451658384:ios:6e5ffa6a92eddecb293015',
    messagingSenderId: '359451658384',
    projectId: 'hw7thing',
    storageBucket: 'hw7thing.appspot.com',
    iosBundleId: 'com.example.bookme.RunnerTests',
  );
}
